name: High 5
favicon: null
layout_spectrum: 0.21983264270238578
typography_spectrum: 0.4122192033100873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#acbf91'
    - '#302f4e'
    - '#889b6d'
    - '#2f5639'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
